# input dataset -> probability ->prediction

# probability
# ===========

# chances of an event likely to happen

# coin >>> gead,tail
# probability(head) =1/2=0.5
# peobability(tail)=1/2=0.5
# p(event)=number of favourable outcomes/total nuumber of outcomes

# types of probability
# ====================


# 1)MARGINAL PROBABILITY
# ======================

# probability of a single event

# total number of students=10
# students who likes python=6
# students who do not like python=4
# p(python)=6/10=0.6
# p(do not like python)=4/10=0.4

# =======================================================================

# 2)JOINT PROBABILITY
# ===================


# To get the probability of two things happening together

# total number of students=10
# students who likes python=6   A
# students who likes Django=4   B
# students who like both python and Django=5

# p(A ^ B)=5/10=0.2
# probability of A and B happening together

# =========================================================================

# 3)CONDITIONAL PROBABILITY
# =========================

# measures the likelyhood of an event happening 
# given that another related event has already occured

# total students=20
# students who knows python=10
# among those 10 students who knows django=6
# p(django|python)
# p(A|B)=p(A ^ B)/p(B)
# P(A given B)=6/10=0.6

